2018-03-05 15:49:00.590 [error] <0.329.0>@erly_room:handle_info:98 erly_room user_join State {room_state,100,10000,[],[]}
2018-03-05 15:49:00.590 [error] <0.326.0>@erly_room_manage:handle_info:111 NewState {state,100,[{room_state,10000,<0.329.0>,1}]}
2018-03-05 15:49:00.605 [error] <0.329.0>@erly_room:handle_info:114 erly_room 10000 NewState {room_state,100,10000,["001"],[]}
2018-03-05 15:49:05.781 [error] <0.326.0>@erly_room_manage:select_exist_room:184 RoomStateList [{10000,<0.329.0>,1}]
2018-03-05 15:49:05.782 [error] <0.326.0>@erly_room_manage:select_exist_room:185 MatchRoomList [{10000,<0.329.0>,1}]
2018-03-05 15:49:05.782 [error] <0.329.0>@erly_room:handle_info:98 erly_room user_join State {room_state,100,10000,["001"],[]}
2018-03-05 15:49:05.782 [error] <0.329.0>@erly_room:handle_info:114 erly_room 10000 NewState {room_state,100,10000,["001","001"],[]}
2018-03-05 15:49:05.783 [error] <0.326.0>@erly_room_manage:handle_info:111 NewState {state,100,[{room_state,10000,<0.329.0>,2}]}
2018-03-05 15:49:19.607 [error] <0.329.0>@erly_room:handle_robot:253 RobotID "robot_1520236159606" join TimeOut 1520236433, Event 6
2018-03-05 15:49:19.607 [error] <0.329.0>@erly_room:broadcast:238 call user = "001" a player join this room name = "robot_1520236159606"
2018-03-05 15:49:19.607 [error] <0.329.0>@erly_room:broadcast:238 call user = "001" a player join this room name = "robot_1520236159606"
2018-03-05 15:49:22.607 [error] <0.329.0>@erly_room:handle_robot:253 RobotID "robot_1520236162607" join TimeOut 1520236418, Event 5
2018-03-05 15:49:22.607 [error] <0.329.0>@erly_room:broadcast:238 call user = "001" a player join this room name = "robot_1520236162607"
2018-03-05 15:49:22.607 [error] <0.329.0>@erly_room:broadcast:238 call user = "001" a player join this room name = "robot_1520236162607"
2018-03-05 15:49:23.784 [error] <0.329.0>@erly_room:handle_robot:253 RobotID "robot_1520236163784" join TimeOut 1520236434, Event 6
2018-03-05 15:49:23.784 [error] <0.329.0>@erly_room:broadcast:238 call user = "001" a player join this room name = "robot_1520236163784"
2018-03-05 15:49:23.784 [error] <0.329.0>@erly_room:broadcast:238 call user = "001" a player join this room name = "robot_1520236163784"
2018-03-05 15:49:24.564 [error] <0.326.0>@erly_room_manage:select_exist_room:184 RoomStateList [{10000,<0.329.0>,2}]
2018-03-05 15:49:24.565 [error] <0.326.0>@erly_room_manage:select_exist_room:185 MatchRoomList [{10000,<0.329.0>,2}]
2018-03-05 15:49:24.565 [error] <0.329.0>@erly_room:handle_info:98 erly_room user_join State {room_state,100,10000,["001","001"],[{robot_list,"robot_1520236159606",1520236433,6},{robot_list,"robot_1520236162607",1520236418,5},{robot_list,"robot_1520236163784",1520236434,6}]}
2018-03-05 15:49:24.565 [error] <0.329.0>@erly_room:broadcast:238 call user = "001" a player join this room name = "001"
2018-03-05 15:49:24.568 [error] <0.326.0>@erly_room_manage:handle_info:111 NewState {state,100,[{room_state,10000,<0.329.0>,3}]}
2018-03-05 15:49:24.568 [error] <0.329.0>@erly_room:handle_info:114 erly_room 10000 NewState {room_state,100,10000,["001","001","001"],[{robot_list,"robot_1520236159606",1520236433,6},{robot_list,"robot_1520236162607",1520236418,5},{robot_list,"robot_1520236163784",1520236434,6}]}
2018-03-05 15:52:15.621 [error] <0.347.0>@erly_room:handle_info:98 erly_room user_join State {room_state,100,10000,[],[]}
2018-03-05 15:52:15.622 [error] <0.344.0>@erly_room_manage:handle_info:111 NewState {state,100,[{room_state,10000,<0.347.0>,1}]}
2018-03-05 15:52:15.633 [error] <0.347.0>@erly_room:handle_info:114 erly_room 10000 NewState {room_state,100,10000,["001"],[]}
2018-03-05 15:52:22.788 [error] <0.344.0>@erly_room_manage:select_exist_room:184 RoomStateList [{10000,<0.347.0>,1}]
2018-03-05 15:52:22.788 [error] <0.344.0>@erly_room_manage:select_exist_room:185 MatchRoomList [{10000,<0.347.0>,1}]
2018-03-05 15:52:22.789 [error] <0.347.0>@erly_room:handle_info:98 erly_room user_join State {room_state,100,10000,["001"],[]}
2018-03-05 15:52:22.789 [error] <0.347.0>@erly_room:handle_info:111 user "001" had join this room
2018-03-05 15:52:22.789 [error] <0.347.0>@erly_room:handle_info:114 erly_room 10000 NewState {room_state,100,10000,["001"],[]}
2018-03-05 15:52:22.792 [error] <0.344.0>@erly_room_manage:handle_info:111 NewState {state,100,[{room_state,10000,<0.347.0>,1}]}
2018-03-05 15:52:33.635 [error] <0.347.0>@erly_room:handle_robot:253 RobotID "robot_1520236353635" join TimeOut 1520236442, Event 4
2018-03-05 15:52:33.636 [error] <0.347.0>@erly_room:broadcast:238 call user = "001" a player join this room name = "robot_1520236353635"
2018-03-05 15:52:37.634 [error] <0.347.0>@erly_room:handle_robot:253 RobotID "robot_1520236357634" join TimeOut 1520236603, Event 3
2018-03-05 15:52:37.635 [error] <0.347.0>@erly_room:broadcast:238 call user = "001" a player join this room name = "robot_1520236357634"
2018-03-05 15:52:41.793 [error] <0.347.0>@erly_room:handle_robot:253 RobotID "robot_1520236361793" join TimeOut 1520236484, Event 4
2018-03-05 15:52:41.793 [error] <0.347.0>@erly_room:broadcast:238 call user = "001" a player join this room name = "robot_1520236361793"
2018-03-05 15:53:00.483 [error] <0.344.0>@erly_room_manage:select_exist_room:184 RoomStateList [{10000,<0.347.0>,1}]
2018-03-05 15:53:00.483 [error] <0.344.0>@erly_room_manage:select_exist_room:185 MatchRoomList [{10000,<0.347.0>,1}]
2018-03-05 15:53:00.484 [error] <0.347.0>@erly_room:handle_info:98 erly_room user_join State {room_state,100,10000,["001"],[{robot_list,"robot_1520236353635",1520236442,4},{robot_list,"robot_1520236357634",1520236603,3},{robot_list,"robot_1520236361793",1520236484,4}]}
2018-03-05 15:53:00.484 [error] <0.347.0>@erly_room:handle_info:111 user "001" had join this room
2018-03-05 15:53:00.484 [error] <0.344.0>@erly_room_manage:handle_info:111 NewState {state,100,[{room_state,10000,<0.347.0>,1}]}
2018-03-05 15:53:00.484 [error] <0.347.0>@erly_room:handle_info:114 erly_room 10000 NewState {room_state,100,10000,["001"],[{robot_list,"robot_1520236353635",1520236442,4},{robot_list,"robot_1520236357634",1520236603,3},{robot_list,"robot_1520236361793",1520236484,4}]}
2018-03-06 10:06:00.554 [error] <0.347.0>@erly_room:handle_robot:265 now time is 1520301960, add robot time is 200000
2018-03-06 10:06:00.554 [error] <0.347.0>@erly_room:handle_robot:265 now time is 1520301960, add robot time is 220000
2018-03-06 10:09:20.556 [error] <0.347.0>@erly_room:handle_robot:265 now time is 1520302160, add robot time is 204000
2018-03-06 10:28:58.815 [error] <0.347.0>@erly_room:handle_robot:265 now time is 1520303338, add robot time is 211000
2018-03-06 10:32:29.817 [error] <0.347.0>@erly_room:handle_robot:265 now time is 1520303549, add robot time is 226000
2018-03-06 10:36:15.819 [error] <0.347.0>@erly_room:handle_robot:265 now time is 1520303775, add robot time is 191000
2018-03-06 10:43:33.096 [error] <0.418.0> CRASH REPORT Process <0.418.0> with 0 neighbours exited with reason: bad argument in call to erlang:register(observer, <0.418.0>) in observer_wx:init/1 line 103
2018-03-06 10:43:36.600 [error] <0.420.0> CRASH REPORT Process <0.420.0> with 0 neighbours exited with reason: bad argument in call to erlang:register(observer, <0.420.0>) in observer_wx:init/1 line 103
2018-03-06 17:50:18.324 [error] <0.327.0> Supervisor room_sup_100 had child erly_room started with erly_room:start_link({100,10000}) at <0.329.0> exit with reason killed in context child_terminated
2018-03-06 17:51:18.156 [error] <0.327.0> Supervisor room_sup_100 had child erly_room started with erly_room:start_link({100,10000}) at <0.363.0> exit with reason killed in context child_terminated
2018-03-07 18:24:22.194 [error] <0.349.0> gen_server <0.349.0> terminated with reason: {'module could not be loaded',[{erly_player_send,send_player,["001",10,#{cmd => joinRoomResp,msg => #{player_list => []}}],[]},{erly_room,broadcast,4,[{file,"/home/henry/erly_room/_build/default/lib/erly_room/src/erly_room.erl"},{line,247}]},{erly_room,handle_info,2,[{file,"/home/henry/erly_room/_build/default/lib/erly_room/src/erly_room.erl"},{line,111}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,601}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,667}]},{proc_lib,...}]}
2018-03-07 18:24:22.234 [error] <0.349.0> CRASH REPORT Process <0.349.0> with 0 neighbours exited with reason: call to undefined function erly_player_send:send_player("001", 10, #{cmd => joinRoomResp,msg => #{player_list => []}}) in gen_server:terminate/7 line 812
2018-03-07 18:24:22.235 [error] <0.345.0> Supervisor room_sup_10 had child erly_room started with erly_room:start_link({10,10000}) at <0.349.0> exit with reason call to undefined function erly_player_send:send_player("001", 10, #{cmd => joinRoomResp,msg => #{player_list => []}}) in context child_terminated
2018-03-08 17:14:26.595 [error] <0.353.0> CRASH REPORT Process <0.353.0> with 0 neighbours exited with reason: {bad_start_spec,[{erly_room_worker,{erly_room_worker,start_link,[]},permanent,brutal_kill,worker,[erly_room_worker]},{erly_room_manage,{erly_room_manage,start_link,[1000]},permanent,5000,worker,[erly_room_manage]}]} in gen_server:init_it/6 line 344
2018-03-08 17:26:04.340 [error] <0.392.0> gen_server erly_room_manage_100 terminated with reason: no match of right hand value {error,{'EXIT',{undef,[{erly_room_woker,start_link,[{100,10000}],[]},{supervisor,do_start_child_i,3,[{file,"supervisor.erl"},{line,381}]},{supervisor,handle_call,3,[{file,"supervisor.erl"},{line,406}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,615}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,647}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}} in erly_room_manage:create_room/2 line 209
2018-03-08 17:26:04.363 [error] <0.392.0> CRASH REPORT Process erly_room_manage_100 with 0 neighbours exited with reason: no match of right hand value {error,{'EXIT',{undef,[{erly_room_woker,start_link,[{100,10000}],[]},{supervisor,do_start_child_i,3,[{file,"supervisor.erl"},{line,381}]},{supervisor,handle_call,3,[{file,"supervisor.erl"},{line,406}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,615}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,647}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}} in erly_room_manage:create_room/2 line 209 in gen_server:terminate/7 line 812
2018-03-08 17:26:04.363 [error] <0.391.0> Supervisor erly_room_sup_100 had child erly_room_manage started with erly_room_manage:start_link(100) at <0.392.0> exit with reason no match of right hand value {error,{'EXIT',{undef,[{erly_room_woker,start_link,[{100,10000}],[]},{supervisor,do_start_child_i,3,[{file,"supervisor.erl"},{line,381}]},{supervisor,handle_call,3,[{file,"supervisor.erl"},{line,406}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,615}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,647}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}} in erly_room_manage:create_room/2 line 209 in context child_terminated
2018-03-08 17:31:43.556 [error] <0.335.0> gen_server <0.335.0> terminated with reason: {'module could not be loaded',[{erly_player_send,send_player,["100",100,#{cmd => joinRoomResp,msg => #{player_list => []}}],[]},{erly_room_worker,broadcast,4,[{file,"/home/henry/erly_room/_build/default/lib/erly_room/src/erly_room_worker.erl"},{line,247}]},{erly_room_worker,handle_info,2,[{file,"/home/henry/erly_room/_build/default/lib/erly_room/src/erly_room_worker.erl"},{line,111}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,601}]},{gen_server,handle_msg,5,[{file,"gen_serve..."},...]},...]}
2018-03-08 17:31:43.564 [error] <0.335.0> CRASH REPORT Process <0.335.0> with 0 neighbours exited with reason: call to undefined function erly_player_send:send_player("100", 100, #{cmd => joinRoomResp,msg => #{player_list => []}}) in gen_server:terminate/7 line 812
2018-03-08 17:31:43.564 [error] <0.333.0> Supervisor room_sup_100 had child erly_room_worker started with erly_room_worker:start_link({100,10000}) at <0.335.0> exit with reason call to undefined function erly_player_send:send_player("100", 100, #{cmd => joinRoomResp,msg => #{player_list => []}}) in context child_terminated
2018-03-08 17:34:06.825 [error] <0.359.0> gen_server <0.359.0> terminated with reason: {'module could not be loaded',[{erly_player_send,send_player,["001",100,#{cmd => joinRoomResp,msg => #{player_list => []}}],[]},{erly_room_worker,broadcast,4,[{file,"/home/henry/erly_room/_build/default/lib/erly_room/src/erly_room_worker.erl"},{line,247}]},{erly_room_worker,handle_info,2,[{file,"/home/henry/erly_room/_build/default/lib/erly_room/src/erly_room_worker.erl"},{line,111}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,601}]},{gen_server,handle_msg,5,[{file,"gen_serve..."},...]},...]}
2018-03-08 17:34:06.837 [error] <0.359.0> CRASH REPORT Process <0.359.0> with 0 neighbours exited with reason: call to undefined function erly_player_send:send_player("001", 100, #{cmd => joinRoomResp,msg => #{player_list => []}}) in gen_server:terminate/7 line 812
2018-03-08 17:34:06.838 [error] <0.357.0> Supervisor erly_room_worker_sup_100 had child erly_room_worker started with erly_room_worker:start_link({100,10000}) at <0.359.0> exit with reason call to undefined function erly_player_send:send_player("001", 100, #{cmd => joinRoomResp,msg => #{player_list => []}}) in context child_terminated
2018-03-08 17:36:35.893 [error] <0.353.0> gen_server <0.353.0> terminated with reason: {'module could not be loaded',[{erly_player_send,send_player,["001",100,#{cmd => joinRoomResp,msg => #{player_list => []}}],[]},{erly_room_worker,broadcast,4,[{file,"/home/henry/erly_room/_build/default/lib/erly_room/src/erly_room_worker.erl"},{line,247}]},{erly_room_worker,handle_info,2,[{file,"/home/henry/erly_room/_build/default/lib/erly_room/src/erly_room_worker.erl"},{line,111}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,601}]},{gen_server,handle_msg,5,[{file,"gen_serve..."},...]},...]}
2018-03-08 17:36:35.906 [error] <0.353.0> CRASH REPORT Process <0.353.0> with 0 neighbours exited with reason: call to undefined function erly_player_send:send_player("001", 100, #{cmd => joinRoomResp,msg => #{player_list => []}}) in gen_server:terminate/7 line 812
2018-03-08 17:36:35.907 [error] <0.351.0> Supervisor erly_room_worker_sup_100 had child erly_room_worker started with erly_room_worker:start_link({100,10000}) at <0.353.0> exit with reason call to undefined function erly_player_send:send_player("001", 100, #{cmd => joinRoomResp,msg => #{player_list => []}}) in context child_terminated
2018-03-09 10:48:05.790 [error] <0.370.0>@erly_room_worker:handle_robot:316 now time is 1520563685, add robot time is 212000
2018-03-09 10:51:37.791 [error] <0.370.0>@erly_room_worker:handle_robot:316 now time is 1520563897, add robot time is 192000
2018-03-09 10:54:49.794 [error] <0.370.0>@erly_room_worker:handle_robot:316 now time is 1520564089, add robot time is 199000
2018-03-09 11:22:07.714 [error] <0.329.0> gen_server <0.329.0> terminated with reason: no function clause matching erly_room_manage:refresh_room_num(100, {refresh_room_num,user_join,0,10000,"001",1}) line 73
2018-03-09 11:22:07.735 [error] <0.329.0> CRASH REPORT Process <0.329.0> with 0 neighbours exited with reason: no function clause matching erly_room_manage:refresh_room_num(100, {refresh_room_num,user_join,0,10000,"001",1}) line 73 in gen_server:terminate/7 line 812
2018-03-09 11:22:07.736 [error] <0.327.0> Supervisor erly_room_worker_sup_100 had child erly_room_worker started with erly_room_worker:start_link({100,10000}) at <0.329.0> exit with reason no function clause matching erly_room_manage:refresh_room_num(100, {refresh_room_num,user_join,0,10000,"001",1}) line 73 in context child_terminated
2018-03-12 13:09:46.506 [error] <0.384.0> Supervisor erly_room_worker_sup_100 had child erly_room_worker started with erly_room_worker:start_link({100,10000}) at <0.386.0> exit with reason killed in context child_terminated
2018-03-12 13:10:06.487 [error] <0.384.0> Supervisor erly_room_worker_sup_100 had child erly_room_worker started with erly_room_worker:start_link({100,10000}) at <0.415.0> exit with reason killed in context child_terminated
2018-03-12 13:10:13.545 [error] <0.384.0> Supervisor erly_room_worker_sup_100 had child erly_room_worker started with erly_room_worker:start_link({100,10000}) at <0.419.0> exit with reason killed in context child_terminated
2018-03-12 13:18:21.980 [error] <0.384.0> Supervisor erly_room_worker_sup_100 had child erly_room_worker started with erly_room_worker:start_link({100,10000}) at <0.424.0> exit with reason killed in context child_terminated
2018-03-12 13:23:28.093 [error] <0.345.0> Supervisor erly_room_worker_sup_100 had child erly_room_worker started with erly_room_worker:start_link({100,10000}) at <0.347.0> exit with reason stop in context child_terminated
2018-03-12 13:25:41.120 [error] <0.345.0> Supervisor erly_room_worker_sup_100 had child erly_room_worker started with erly_room_worker:start_link({100,10000}) at <0.347.0> exit with reason stop in context child_terminated
2018-03-12 13:26:40.225 [error] <0.345.0> Supervisor erly_room_worker_sup_100 had child erly_room_worker started with erly_room_worker:start_link({100,10000}) at <0.350.0> exit with reason shutdown in context child_terminated
2018-03-12 13:29:58.750 [error] <0.345.0> Supervisor erly_room_worker_sup_10 had child erly_room_worker started with erly_room_worker:start_link({10,10000}) at <0.347.0> exit with reason shutdown in context child_terminated
2018-03-12 13:52:06.025 [error] <0.345.0> Supervisor erly_room_worker_sup_10 had child erly_room_worker started with erly_room_worker:start_link({10,10000}) at <0.347.0> exit with reason shutdown in context child_terminated
2018-03-12 14:12:08.163 [error] <0.345.0> Supervisor erly_room_worker_sup_10 had child erly_room_worker started with erly_room_worker:start_link({10,10000}) at <0.350.0> exit with reason aaaa in context child_terminated
2018-03-12 14:20:17.753 [error] <0.351.0> Supervisor erly_room_worker_sup_10 had child erly_room_worker started with erly_room_worker:start_link({10,10000}) at <0.354.0> exit with reason xxx in context child_terminated
2018-03-19 17:29:31.031 [error] <0.344.0> gen_server erly_room_manage_10 terminated with reason: no function clause matching gen_server:reply(<0.344.0>, 10000) line 240
2018-03-19 17:29:31.065 [error] <0.344.0> CRASH REPORT Process erly_room_manage_10 with 0 neighbours exited with reason: no function clause matching gen_server:reply(<0.344.0>, 10000) line 240 in gen_server:terminate/7 line 812
2018-03-19 17:29:31.067 [error] <0.343.0> Supervisor erly_room_sup_10 had child erly_room_manage started with erly_room_manage:start_link(10) at <0.344.0> exit with reason no function clause matching gen_server:reply(<0.344.0>, 10000) line 240 in context child_terminated
2018-03-20 14:45:07.718 [error] <0.337.0> CRASH REPORT Process <0.337.0> with 0 neighbours exited with reason: bad argument in gproc:chk_reply/2 line 1279
2018-03-20 14:47:34.818 [error] <0.332.0> CRASH REPORT Process <0.332.0> with 0 neighbours exited with reason: bad argument in gproc:chk_reply/2 line 1279
2018-03-20 14:48:45.261 [error] <0.338.0> CRASH REPORT Process <0.338.0> with 0 neighbours exited with reason: bad argument in gproc:chk_reply/2 line 1279
2018-03-20 14:51:08.991 [error] <0.347.0> CRASH REPORT Process <0.347.0> with 0 neighbours exited with reason: bad argument in gproc:chk_reply/2 line 1279
2018-03-20 14:53:58.518 [error] <0.332.0> CRASH REPORT Process <0.332.0> with 0 neighbours exited with reason: bad argument in gproc:chk_reply/2 line 1279
2018-03-20 15:05:00.592 [error] <0.350.0> CRASH REPORT Process <0.350.0> with 0 neighbours exited with reason: bad argument in gproc:chk_reply/2 line 1279
2018-03-23 14:07:32.425 [error] <0.329.0> gen_server <0.329.0> terminated with reason: no function clause matching erly_room_worker:'-filter_user_list_get_user_id/1-fun-0-'(123) line 348
2018-03-23 14:07:32.470 [error] <0.329.0> CRASH REPORT Process <0.329.0> with 0 neighbours exited with reason: no function clause matching erly_room_worker:'-filter_user_list_get_user_id/1-fun-0-'(123) line 348 in gen_server:terminate/7 line 812
2018-03-23 14:07:32.472 [error] <0.327.0> Supervisor erly_room_worker_sup_10 had child erly_room_worker started with erly_room_worker:start_link({10,10000}) at <0.329.0> exit with reason no function clause matching erly_room_worker:'-filter_user_list_get_user_id/1-fun-0-'(123) line 348 in context child_terminated
2018-03-23 14:13:41.015 [error] <0.365.0> gen_server <0.365.0> terminated with reason: no function clause matching erly_room_worker:'-filter_user_list_get_user_id/1-fun-0-'(123) line 349
2018-03-23 14:13:41.031 [error] <0.365.0> CRASH REPORT Process <0.365.0> with 0 neighbours exited with reason: no function clause matching erly_room_worker:'-filter_user_list_get_user_id/1-fun-0-'(123) line 349 in gen_server:terminate/7 line 812
2018-03-23 14:13:41.032 [error] <0.363.0> Supervisor erly_room_worker_sup_10 had child erly_room_worker started with erly_room_worker:start_link({10,10000}) at <0.365.0> exit with reason no function clause matching erly_room_worker:'-filter_user_list_get_user_id/1-fun-0-'(123) line 349 in context child_terminated
2018-03-23 16:06:13.333 [error] <0.381.0> gen_server <0.381.0> terminated with reason: no function clause matching erly_room_worker:'-return_robot_info/1-fun-0-'("robot_1521792373333") line 381
2018-03-23 16:06:13.340 [error] <0.381.0> CRASH REPORT Process <0.381.0> with 0 neighbours exited with reason: no function clause matching erly_room_worker:'-return_robot_info/1-fun-0-'("robot_1521792373333") line 381 in gen_server:terminate/7 line 812
2018-03-23 16:06:13.341 [error] <0.379.0> Supervisor erly_room_worker_sup_10 had child erly_room_worker started with erly_room_worker:start_link({10,10000}) at <0.381.0> exit with reason no function clause matching erly_room_worker:'-return_robot_info/1-fun-0-'("robot_1521792373333") line 381 in context child_terminated
2018-03-23 16:09:08.942 [error] <0.347.0> gen_server <0.347.0> terminated with reason: no function clause matching erly_room_worker:'-return_robot_info/1-fun-0-'({"robot_1521792548941","tzymy0ebgg",5}) line 381
2018-03-23 16:09:08.948 [error] <0.347.0> CRASH REPORT Process <0.347.0> with 0 neighbours exited with reason: no function clause matching erly_room_worker:'-return_robot_info/1-fun-0-'({"robot_1521792548941","tzymy0ebgg",5}) line 381 in gen_server:terminate/7 line 812
2018-03-23 16:09:08.949 [error] <0.345.0> Supervisor erly_room_worker_sup_10 had child erly_room_worker started with erly_room_worker:start_link({10,10000}) at <0.347.0> exit with reason no function clause matching erly_room_worker:'-return_robot_info/1-fun-0-'({"robot_1521792548941","tzymy0ebgg",5}) line 381 in context child_terminated
2018-03-23 16:27:48.835 [error] <0.347.0> gen_server <0.347.0> terminated with reason: no function clause matching string:substr2([], 3) line 213
2018-03-23 16:27:48.847 [error] <0.347.0> CRASH REPORT Process <0.347.0> with 0 neighbours exited with reason: no function clause matching string:substr2([], 3) line 213 in gen_server:terminate/7 line 812
2018-03-23 16:27:48.849 [error] <0.345.0> Supervisor erly_room_worker_sup_10 had child erly_room_worker started with erly_room_worker:start_link({10,10000}) at <0.347.0> exit with reason no function clause matching string:substr2([], 3) line 213 in context child_terminated
2018-03-23 16:29:05.306 [error] <0.347.0> gen_server <0.347.0> terminated with reason: no function clause matching string:substr2([], 3) line 213
2018-03-23 16:29:05.315 [error] <0.347.0> CRASH REPORT Process <0.347.0> with 0 neighbours exited with reason: no function clause matching string:substr2([], 3) line 213 in gen_server:terminate/7 line 812
2018-03-23 16:29:05.317 [error] <0.345.0> Supervisor erly_room_worker_sup_10 had child erly_room_worker started with erly_room_worker:start_link({10,10000}) at <0.347.0> exit with reason no function clause matching string:substr2([], 3) line 213 in context child_terminated
2018-03-26 09:37:51.106 [error] <0.357.0>@erly_room_worker:handle_cast:164 get msg {user_join,10000,"001"}
2018-03-26 09:37:51.106 [error] <0.357.0> gen_server <0.357.0> terminated with reason: {unknown_cast,{user_join,10000,"001"}}
2018-03-26 09:37:51.147 [error] <0.357.0> CRASH REPORT Process <0.357.0> with 0 neighbours exited with reason: {unknown_cast,{user_join,10000,"001"}} in gen_server:terminate/7 line 812
2018-03-26 09:37:51.147 [error] <0.355.0> Supervisor erly_room_worker_sup_10 had child erly_room_worker started with erly_room_worker:start_link({10,10000}) at <0.357.0> exit with reason {unknown_cast,{user_join,10000,"001"}} in context child_terminated
2018-03-26 09:38:57.309 [error] <0.359.0> gen_server <0.359.0> terminated with reason: no function clause matching string:substr2([], 2) line 213
2018-03-26 09:38:57.309 [error] <0.359.0> CRASH REPORT Process <0.359.0> with 0 neighbours exited with reason: no function clause matching string:substr2([], 2) line 213 in gen_server:terminate/7 line 812
2018-03-26 09:38:57.311 [error] <0.355.0> Supervisor erly_room_worker_sup_10 had child erly_room_worker started with erly_room_worker:start_link({10,10000}) at <0.359.0> exit with reason no function clause matching string:substr2([], 2) line 213 in context child_terminated
2018-03-26 09:41:38.190 [error] <0.362.0> gen_server <0.362.0> terminated with reason: no function clause matching string:substr2([], 2) line 213
2018-03-26 09:41:38.191 [error] <0.362.0> CRASH REPORT Process <0.362.0> with 0 neighbours exited with reason: no function clause matching string:substr2([], 2) line 213 in gen_server:terminate/7 line 812
2018-03-26 09:41:38.196 [error] <0.355.0> Supervisor erly_room_worker_sup_10 had child erly_room_worker started with erly_room_worker:start_link({10,10000}) at <0.362.0> exit with reason no function clause matching string:substr2([], 2) line 213 in context child_terminated
2018-03-26 09:52:45.032 [error] <0.327.0> Supervisor erly_room_worker_sup_1 had child erly_room_worker started with erly_room_worker:start_link({1,10000}) at <0.330.0> exit with reason shutdown in context child_terminated
2018-03-26 09:54:04.767 [error] <0.327.0> Supervisor erly_room_worker_sup_1 had child erly_room_worker started with erly_room_worker:start_link({1,10000}) at <0.521.0> exit with reason killed in context child_terminated
2018-03-26 09:55:05.697 [error] <0.327.0> Supervisor erly_room_worker_sup_1 had child erly_room_worker started with erly_room_worker:start_link({1,10000}) at <0.527.0> exit with reason stop in context child_terminated
2018-03-26 09:57:47.626 [error] <0.528.0> Supervisor erly_room_worker_sup_10 had child erly_room_worker started with erly_room_worker:start_link({10,10000}) at <0.531.0> exit with reason killed in context child_terminated
2018-03-26 10:03:44.381 [error] <0.542.0>@erly_room_worker:handle_info:248 get msg {'EXIT',<0.364.0>,normal}
2018-03-26 10:08:23.714 [error] <0.347.0> gen_server <0.347.0> terminated with reason: bad arithmetic expression in erly_room_worker:handle_call/3 line 115
2018-03-26 10:08:23.733 [error] <0.347.0> CRASH REPORT Process <0.347.0> with 0 neighbours exited with reason: bad arithmetic expression in erly_room_worker:handle_call/3 line 115 in gen_server:terminate/7 line 812
2018-03-26 10:08:23.734 [error] <0.345.0> Supervisor erly_room_worker_sup_10 had child erly_room_worker started with erly_room_worker:start_link({10,10000}) at <0.347.0> exit with reason bad arithmetic expression in erly_room_worker:handle_call/3 line 115 in context child_terminated
2018-03-26 10:15:15.654 [error] <0.348.0> gen_server <0.348.0> terminated with reason: bad arithmetic expression in erly_room_worker:handle_call/3 line 112
2018-03-26 10:15:15.673 [error] <0.348.0> CRASH REPORT Process <0.348.0> with 0 neighbours exited with reason: bad arithmetic expression in erly_room_worker:handle_call/3 line 112 in gen_server:terminate/7 line 812
2018-03-26 10:15:15.673 [error] <0.346.0> Supervisor erly_room_worker_sup_10 had child erly_room_worker started with erly_room_worker:start_link({10,10000}) at <0.348.0> exit with reason bad arithmetic expression in erly_room_worker:handle_call/3 line 112 in context child_terminated
2018-03-26 10:50:55.424 [error] <0.347.0>@erly_room_worker:terminate:269 process terminate Reason {badarith,[{erly_room_worker,handle_call,3,[{file,"/home/henry/erly_room/_build/default/lib/erly_room/src/erly_room_worker.erl"},{line,122}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,615}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,647}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
2018-03-26 10:50:55.425 [error] <0.347.0> gen_server <0.347.0> terminated with reason: bad arithmetic expression in erly_room_worker:handle_call/3 line 122
2018-03-26 10:50:55.444 [error] <0.347.0> CRASH REPORT Process <0.347.0> with 0 neighbours exited with reason: bad arithmetic expression in erly_room_worker:handle_call/3 line 122 in gen_server:terminate/7 line 812
2018-03-26 10:50:55.445 [error] <0.345.0> Supervisor erly_room_worker_sup_10 had child erly_room_worker started with erly_room_worker:start_link({10,10000}) at <0.347.0> exit with reason bad arithmetic expression in erly_room_worker:handle_call/3 line 122 in context child_terminated
2018-03-26 10:50:55.447 [error] <0.352.0> CRASH REPORT Process <0.352.0> with 0 neighbours exited with reason: bad argument in call to ets:lookup(room_data, {10,10000}) in erly_room_worker:init/1 line 102
2018-03-26 10:50:55.451 [error] <0.345.0> Supervisor erly_room_worker_sup_10 had child erly_room_worker started with erly_room_worker:start_link({10,10000}) at <0.347.0> exit with reason bad argument in call to ets:lookup(room_data, {10,10000}) in erly_room_worker:init/1 line 102 in context start_error
2018-03-26 10:50:55.452 [error] <0.353.0> CRASH REPORT Process <0.353.0> with 0 neighbours exited with reason: bad argument in call to ets:lookup(room_data, {10,10000}) in erly_room_worker:init/1 line 102
2018-03-26 10:50:55.453 [error] <0.345.0> Supervisor erly_room_worker_sup_10 had child erly_room_worker started with erly_room_worker:start_link({10,10000}) at {restarting,<0.347.0>} exit with reason bad argument in call to ets:lookup(room_data, {10,10000}) in erly_room_worker:init/1 line 102 in context start_error
2018-03-26 10:50:55.454 [error] <0.354.0> CRASH REPORT Process <0.354.0> with 0 neighbours exited with reason: bad argument in call to ets:lookup(room_data, {10,10000}) in erly_room_worker:init/1 line 102
2018-03-26 10:50:55.454 [error] <0.345.0> Supervisor erly_room_worker_sup_10 had child erly_room_worker started with erly_room_worker:start_link({10,10000}) at {restarting,<0.347.0>} exit with reason bad argument in call to ets:lookup(room_data, {10,10000}) in erly_room_worker:init/1 line 102 in context start_error
2018-03-26 10:50:55.454 [error] <0.355.0> CRASH REPORT Process <0.355.0> with 0 neighbours exited with reason: bad argument in call to ets:lookup(room_data, {10,10000}) in erly_room_worker:init/1 line 102
2018-03-26 10:50:55.455 [error] <0.345.0> Supervisor erly_room_worker_sup_10 had child erly_room_worker started with erly_room_worker:start_link({10,10000}) at {restarting,<0.347.0>} exit with reason bad argument in call to ets:lookup(room_data, {10,10000}) in erly_room_worker:init/1 line 102 in context start_error
2018-03-26 10:50:55.455 [error] <0.356.0> CRASH REPORT Process <0.356.0> with 0 neighbours exited with reason: bad argument in call to ets:lookup(room_data, {10,10000}) in erly_room_worker:init/1 line 102
2018-03-26 10:50:55.456 [error] <0.345.0> Supervisor erly_room_worker_sup_10 had child erly_room_worker started with erly_room_worker:start_link({10,10000}) at {restarting,<0.347.0>} exit with reason bad argument in call to ets:lookup(room_data, {10,10000}) in erly_room_worker:init/1 line 102 in context start_error
2018-03-26 10:50:55.456 [error] <0.357.0> CRASH REPORT Process <0.357.0> with 0 neighbours exited with reason: bad argument in call to ets:lookup(room_data, {10,10000}) in erly_room_worker:init/1 line 102
2018-03-26 10:50:55.456 [error] <0.345.0> Supervisor erly_room_worker_sup_10 had child erly_room_worker started with erly_room_worker:start_link({10,10000}) at {restarting,<0.347.0>} exit with reason bad argument in call to ets:lookup(room_data, {10,10000}) in erly_room_worker:init/1 line 102 in context start_error
2018-03-26 10:50:55.457 [error] <0.358.0> CRASH REPORT Process <0.358.0> with 0 neighbours exited with reason: bad argument in call to ets:lookup(room_data, {10,10000}) in erly_room_worker:init/1 line 102
2018-03-26 10:50:55.457 [error] <0.345.0> Supervisor erly_room_worker_sup_10 had child erly_room_worker started with erly_room_worker:start_link({10,10000}) at {restarting,<0.347.0>} exit with reason bad argument in call to ets:lookup(room_data, {10,10000}) in erly_room_worker:init/1 line 102 in context start_error
2018-03-26 10:50:55.457 [error] <0.359.0> CRASH REPORT Process <0.359.0> with 0 neighbours exited with reason: bad argument in call to ets:lookup(room_data, {10,10000}) in erly_room_worker:init/1 line 102
2018-03-26 10:50:55.458 [error] <0.345.0> Supervisor erly_room_worker_sup_10 had child erly_room_worker started with erly_room_worker:start_link({10,10000}) at {restarting,<0.347.0>} exit with reason bad argument in call to ets:lookup(room_data, {10,10000}) in erly_room_worker:init/1 line 102 in context start_error
2018-03-26 10:50:55.459 [error] <0.360.0> CRASH REPORT Process <0.360.0> with 0 neighbours exited with reason: bad argument in call to ets:lookup(room_data, {10,10000}) in erly_room_worker:init/1 line 102
2018-03-26 10:50:55.459 [error] <0.345.0> Supervisor erly_room_worker_sup_10 had child erly_room_worker started with erly_room_worker:start_link({10,10000}) at {restarting,<0.347.0>} exit with reason bad argument in call to ets:lookup(room_data, {10,10000}) in erly_room_worker:init/1 line 102 in context start_error
2018-03-26 10:50:55.459 [error] <0.361.0> CRASH REPORT Process <0.361.0> with 0 neighbours exited with reason: bad argument in call to ets:lookup(room_data, {10,10000}) in erly_room_worker:init/1 line 102
2018-03-26 10:50:55.460 [error] <0.345.0> Supervisor erly_room_worker_sup_10 had child erly_room_worker started with erly_room_worker:start_link({10,10000}) at {restarting,<0.347.0>} exit with reason bad argument in call to ets:lookup(room_data, {10,10000}) in erly_room_worker:init/1 line 102 in context start_error
2018-03-26 10:50:55.460 [error] <0.345.0> Supervisor erly_room_worker_sup_10 had child erly_room_worker started with erly_room_worker:start_link({10,10000}) at {restarting,<0.347.0>} exit with reason reached_max_restart_intensity in context shutdown
2018-03-26 10:50:55.460 [error] <0.343.0> Supervisor erly_room_sup_10 had child erly_room_worker_sup started with erly_room_worker_sup:start_link(10) at <0.345.0> exit with reason shutdown in context child_terminated
2018-03-26 10:53:40.984 [error] <0.347.0>@erly_room_worker:terminate:269 process terminate Reason {badarith,[{erly_room_worker,handle_call,3,[{file,"/home/henry/erly_room/_build/default/lib/erly_room/src/erly_room_worker.erl"},{line,122}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,615}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,647}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
2018-03-26 10:53:40.984 [error] <0.347.0> gen_server <0.347.0> terminated with reason: bad arithmetic expression in erly_room_worker:handle_call/3 line 122
2018-03-26 10:53:41.001 [error] <0.347.0> CRASH REPORT Process <0.347.0> with 0 neighbours exited with reason: bad arithmetic expression in erly_room_worker:handle_call/3 line 122 in gen_server:terminate/7 line 812
2018-03-26 10:53:41.002 [error] <0.345.0> Supervisor erly_room_worker_sup_10 had child erly_room_worker started with erly_room_worker:start_link({10,10000}) at <0.347.0> exit with reason bad arithmetic expression in erly_room_worker:handle_call/3 line 122 in context child_terminated
2018-03-26 11:01:09.975 [error] <0.347.0>@erly_room_worker:terminate:269 process terminate Reason {badarith,[{erly_room_worker,handle_call,3,[{file,"/home/henry/erly_room/_build/default/lib/erly_room/src/erly_room_worker.erl"},{line,122}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,615}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,647}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
2018-03-26 11:01:09.975 [error] <0.347.0> gen_server <0.347.0> terminated with reason: bad arithmetic expression in erly_room_worker:handle_call/3 line 122
2018-03-26 11:01:09.989 [error] <0.347.0> CRASH REPORT Process <0.347.0> with 0 neighbours exited with reason: bad arithmetic expression in erly_room_worker:handle_call/3 line 122 in gen_server:terminate/7 line 812
2018-03-26 11:01:09.990 [error] <0.345.0> Supervisor erly_room_worker_sup_10 had child erly_room_worker started with erly_room_worker:start_link({10,10000}) at <0.347.0> exit with reason bad arithmetic expression in erly_room_worker:handle_call/3 line 122 in context child_terminated
2018-03-26 11:06:16.402 [error] <0.347.0>@erly_room_worker:terminate:269 process terminate Reason {badarith,[{erly_room_worker,handle_call,3,[{file,"/home/henry/erly_room/_build/default/lib/erly_room/src/erly_room_worker.erl"},{line,122}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,615}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,647}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
2018-03-26 11:06:16.403 [error] <0.347.0> gen_server <0.347.0> terminated with reason: bad arithmetic expression in erly_room_worker:handle_call/3 line 122
2018-03-26 11:06:16.423 [error] <0.347.0> CRASH REPORT Process <0.347.0> with 0 neighbours exited with reason: bad arithmetic expression in erly_room_worker:handle_call/3 line 122 in gen_server:terminate/7 line 812
2018-03-26 11:06:16.426 [error] <0.345.0> Supervisor erly_room_worker_sup_10 had child erly_room_worker started with erly_room_worker:start_link({10,10000}) at <0.347.0> exit with reason bad arithmetic expression in erly_room_worker:handle_call/3 line 122 in context child_terminated
2018-03-26 11:06:16.428 [error] <0.353.0> CRASH REPORT Process <0.353.0> with 0 neighbours exited with reason: bad argument in call to ets:lookup(room_data, {10,10000}) in erly_room_worker:init/1 line 102
2018-03-26 11:06:16.429 [error] <0.345.0> Supervisor erly_room_worker_sup_10 had child erly_room_worker started with erly_room_worker:start_link({10,10000}) at <0.347.0> exit with reason bad argument in call to ets:lookup(room_data, {10,10000}) in erly_room_worker:init/1 line 102 in context start_error
2018-03-26 11:06:16.430 [error] <0.354.0> CRASH REPORT Process <0.354.0> with 0 neighbours exited with reason: bad argument in call to ets:lookup(room_data, {10,10000}) in erly_room_worker:init/1 line 102
2018-03-26 11:06:16.431 [error] <0.345.0> Supervisor erly_room_worker_sup_10 had child erly_room_worker started with erly_room_worker:start_link({10,10000}) at {restarting,<0.347.0>} exit with reason bad argument in call to ets:lookup(room_data, {10,10000}) in erly_room_worker:init/1 line 102 in context start_error
2018-03-26 11:06:16.432 [error] <0.345.0> Supervisor erly_room_worker_sup_10 had child erly_room_worker started with erly_room_worker:start_link({10,10000}) at {restarting,<0.347.0>} exit with reason bad argument in call to ets:lookup(room_data, {10,10000}) in erly_room_worker:init/1 line 102 in context start_error
2018-03-26 11:06:16.432 [error] <0.355.0> CRASH REPORT Process <0.355.0> with 0 neighbours exited with reason: bad argument in call to ets:lookup(room_data, {10,10000}) in erly_room_worker:init/1 line 102
2018-03-26 11:06:16.434 [error] <0.356.0> CRASH REPORT Process <0.356.0> with 0 neighbours exited with reason: bad argument in call to ets:lookup(room_data, {10,10000}) in erly_room_worker:init/1 line 102
2018-03-26 11:06:16.435 [error] <0.345.0> Supervisor erly_room_worker_sup_10 had child erly_room_worker started with erly_room_worker:start_link({10,10000}) at {restarting,<0.347.0>} exit with reason bad argument in call to ets:lookup(room_data, {10,10000}) in erly_room_worker:init/1 line 102 in context start_error
2018-03-26 11:06:16.438 [error] <0.357.0> CRASH REPORT Process <0.357.0> with 0 neighbours exited with reason: bad argument in call to ets:lookup(room_data, {10,10000}) in erly_room_worker:init/1 line 102
2018-03-26 11:06:16.438 [error] <0.345.0> Supervisor erly_room_worker_sup_10 had child erly_room_worker started with erly_room_worker:start_link({10,10000}) at {restarting,<0.347.0>} exit with reason bad argument in call to ets:lookup(room_data, {10,10000}) in erly_room_worker:init/1 line 102 in context start_error
2018-03-26 11:06:16.438 [error] <0.358.0> CRASH REPORT Process <0.358.0> with 0 neighbours exited with reason: bad argument in call to ets:lookup(room_data, {10,10000}) in erly_room_worker:init/1 line 102
2018-03-26 11:06:16.439 [error] <0.345.0> Supervisor erly_room_worker_sup_10 had child erly_room_worker started with erly_room_worker:start_link({10,10000}) at {restarting,<0.347.0>} exit with reason bad argument in call to ets:lookup(room_data, {10,10000}) in erly_room_worker:init/1 line 102 in context start_error
2018-03-26 11:06:16.439 [error] <0.359.0> CRASH REPORT Process <0.359.0> with 0 neighbours exited with reason: bad argument in call to ets:lookup(room_data, {10,10000}) in erly_room_worker:init/1 line 102
2018-03-26 11:06:16.440 [error] <0.345.0> Supervisor erly_room_worker_sup_10 had child erly_room_worker started with erly_room_worker:start_link({10,10000}) at {restarting,<0.347.0>} exit with reason bad argument in call to ets:lookup(room_data, {10,10000}) in erly_room_worker:init/1 line 102 in context start_error
2018-03-26 11:06:16.440 [error] <0.360.0> CRASH REPORT Process <0.360.0> with 0 neighbours exited with reason: bad argument in call to ets:lookup(room_data, {10,10000}) in erly_room_worker:init/1 line 102
2018-03-26 11:06:16.440 [error] <0.345.0> Supervisor erly_room_worker_sup_10 had child erly_room_worker started with erly_room_worker:start_link({10,10000}) at {restarting,<0.347.0>} exit with reason bad argument in call to ets:lookup(room_data, {10,10000}) in erly_room_worker:init/1 line 102 in context start_error
2018-03-26 11:06:16.440 [error] <0.361.0> CRASH REPORT Process <0.361.0> with 0 neighbours exited with reason: bad argument in call to ets:lookup(room_data, {10,10000}) in erly_room_worker:init/1 line 102
2018-03-26 11:06:16.440 [error] <0.345.0> Supervisor erly_room_worker_sup_10 had child erly_room_worker started with erly_room_worker:start_link({10,10000}) at {restarting,<0.347.0>} exit with reason bad argument in call to ets:lookup(room_data, {10,10000}) in erly_room_worker:init/1 line 102 in context start_error
2018-03-26 11:06:16.440 [error] <0.362.0> CRASH REPORT Process <0.362.0> with 0 neighbours exited with reason: bad argument in call to ets:lookup(room_data, {10,10000}) in erly_room_worker:init/1 line 102
2018-03-26 11:06:16.440 [error] <0.345.0> Supervisor erly_room_worker_sup_10 had child erly_room_worker started with erly_room_worker:start_link({10,10000}) at {restarting,<0.347.0>} exit with reason bad argument in call to ets:lookup(room_data, {10,10000}) in erly_room_worker:init/1 line 102 in context start_error
2018-03-26 11:06:16.440 [error] <0.345.0> Supervisor erly_room_worker_sup_10 had child erly_room_worker started with erly_room_worker:start_link({10,10000}) at {restarting,<0.347.0>} exit with reason reached_max_restart_intensity in context shutdown
2018-03-26 11:06:16.440 [error] <0.343.0> Supervisor erly_room_sup_10 had child erly_room_worker_sup started with erly_room_worker_sup:start_link(10) at <0.345.0> exit with reason shutdown in context child_terminated
2018-03-26 11:11:24.512 [error] <0.327.0> Supervisor erly_room_worker_sup_10 had child erly_room_worker started with erly_room_worker:start_link({10,10000}) at <0.329.0> exit with reason badarith in context child_terminated
2018-03-26 11:14:56.252 [error] <0.329.0>@erly_room_worker:terminate:269 process terminate Reason {badarith,[{erly_room_worker,handle_call,3,[{file,"/home/henry/erly_room/_build/default/lib/erly_room/src/erly_room_worker.erl"},{line,122}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,615}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,647}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
2018-03-26 11:14:56.253 [error] <0.329.0> gen_server <0.329.0> terminated with reason: bad arithmetic expression in erly_room_worker:handle_call/3 line 122
2018-03-26 11:14:56.273 [error] <0.329.0> CRASH REPORT Process <0.329.0> with 0 neighbours exited with reason: bad arithmetic expression in erly_room_worker:handle_call/3 line 122 in gen_server:terminate/7 line 812
2018-03-26 11:14:56.274 [error] <0.327.0> Supervisor erly_room_worker_sup_10 had child erly_room_worker started with erly_room_worker:start_link({10,10000}) at <0.329.0> exit with reason bad arithmetic expression in erly_room_worker:handle_call/3 line 122 in context child_terminated
2018-03-26 11:14:56.274 [error] <0.334.0> CRASH REPORT Process <0.334.0> with 0 neighbours exited with reason: bad argument in call to ets:lookup(room_data, {10,10000}) in erly_room_worker:init/1 line 102
2018-03-26 11:14:56.274 [error] <0.327.0> Supervisor erly_room_worker_sup_10 had child erly_room_worker started with erly_room_worker:start_link({10,10000}) at <0.329.0> exit with reason bad argument in call to ets:lookup(room_data, {10,10000}) in erly_room_worker:init/1 line 102 in context start_error
2018-03-26 11:14:56.275 [error] <0.335.0> CRASH REPORT Process <0.335.0> with 0 neighbours exited with reason: bad argument in call to ets:lookup(room_data, {10,10000}) in erly_room_worker:init/1 line 102
2018-03-26 11:14:56.275 [error] <0.327.0> Supervisor erly_room_worker_sup_10 had child erly_room_worker started with erly_room_worker:start_link({10,10000}) at {restarting,<0.329.0>} exit with reason bad argument in call to ets:lookup(room_data, {10,10000}) in erly_room_worker:init/1 line 102 in context start_error
2018-03-26 11:14:56.275 [error] <0.336.0> CRASH REPORT Process <0.336.0> with 0 neighbours exited with reason: bad argument in call to ets:lookup(room_data, {10,10000}) in erly_room_worker:init/1 line 102
2018-03-26 11:14:56.276 [error] <0.327.0> Supervisor erly_room_worker_sup_10 had child erly_room_worker started with erly_room_worker:start_link({10,10000}) at {restarting,<0.329.0>} exit with reason bad argument in call to ets:lookup(room_data, {10,10000}) in erly_room_worker:init/1 line 102 in context start_error
2018-03-26 11:14:56.276 [error] <0.337.0> CRASH REPORT Process <0.337.0> with 0 neighbours exited with reason: bad argument in call to ets:lookup(room_data, {10,10000}) in erly_room_worker:init/1 line 102
2018-03-26 11:14:56.277 [error] <0.327.0> Supervisor erly_room_worker_sup_10 had child erly_room_worker started with erly_room_worker:start_link({10,10000}) at {restarting,<0.329.0>} exit with reason bad argument in call to ets:lookup(room_data, {10,10000}) in erly_room_worker:init/1 line 102 in context start_error
2018-03-26 11:14:56.277 [error] <0.338.0> CRASH REPORT Process <0.338.0> with 0 neighbours exited with reason: bad argument in call to ets:lookup(room_data, {10,10000}) in erly_room_worker:init/1 line 102
2018-03-26 11:14:56.277 [error] <0.327.0> Supervisor erly_room_worker_sup_10 had child erly_room_worker started with erly_room_worker:start_link({10,10000}) at {restarting,<0.329.0>} exit with reason bad argument in call to ets:lookup(room_data, {10,10000}) in erly_room_worker:init/1 line 102 in context start_error
2018-03-26 11:14:56.277 [error] <0.339.0> CRASH REPORT Process <0.339.0> with 0 neighbours exited with reason: bad argument in call to ets:lookup(room_data, {10,10000}) in erly_room_worker:init/1 line 102
2018-03-26 11:14:56.277 [error] <0.327.0> Supervisor erly_room_worker_sup_10 had child erly_room_worker started with erly_room_worker:start_link({10,10000}) at {restarting,<0.329.0>} exit with reason bad argument in call to ets:lookup(room_data, {10,10000}) in erly_room_worker:init/1 line 102 in context start_error
2018-03-26 11:14:56.277 [error] <0.340.0> CRASH REPORT Process <0.340.0> with 0 neighbours exited with reason: bad argument in call to ets:lookup(room_data, {10,10000}) in erly_room_worker:init/1 line 102
2018-03-26 11:14:56.278 [error] <0.327.0> Supervisor erly_room_worker_sup_10 had child erly_room_worker started with erly_room_worker:start_link({10,10000}) at {restarting,<0.329.0>} exit with reason bad argument in call to ets:lookup(room_data, {10,10000}) in erly_room_worker:init/1 line 102 in context start_error
2018-03-26 11:14:56.278 [error] <0.341.0> CRASH REPORT Process <0.341.0> with 0 neighbours exited with reason: bad argument in call to ets:lookup(room_data, {10,10000}) in erly_room_worker:init/1 line 102
2018-03-26 11:14:56.278 [error] <0.327.0> Supervisor erly_room_worker_sup_10 had child erly_room_worker started with erly_room_worker:start_link({10,10000}) at {restarting,<0.329.0>} exit with reason bad argument in call to ets:lookup(room_data, {10,10000}) in erly_room_worker:init/1 line 102 in context start_error
2018-03-26 11:14:56.278 [error] <0.342.0> CRASH REPORT Process <0.342.0> with 0 neighbours exited with reason: bad argument in call to ets:lookup(room_data, {10,10000}) in erly_room_worker:init/1 line 102
2018-03-26 11:14:56.278 [error] <0.327.0> Supervisor erly_room_worker_sup_10 had child erly_room_worker started with erly_room_worker:start_link({10,10000}) at {restarting,<0.329.0>} exit with reason bad argument in call to ets:lookup(room_data, {10,10000}) in erly_room_worker:init/1 line 102 in context start_error
2018-03-26 11:14:56.278 [error] <0.343.0> CRASH REPORT Process <0.343.0> with 0 neighbours exited with reason: bad argument in call to ets:lookup(room_data, {10,10000}) in erly_room_worker:init/1 line 102
2018-03-26 11:14:56.278 [error] <0.327.0> Supervisor erly_room_worker_sup_10 had child erly_room_worker started with erly_room_worker:start_link({10,10000}) at {restarting,<0.329.0>} exit with reason bad argument in call to ets:lookup(room_data, {10,10000}) in erly_room_worker:init/1 line 102 in context start_error
2018-03-26 11:14:56.279 [error] <0.327.0> Supervisor erly_room_worker_sup_10 had child erly_room_worker started with erly_room_worker:start_link({10,10000}) at {restarting,<0.329.0>} exit with reason reached_max_restart_intensity in context shutdown
2018-03-26 11:14:56.279 [error] <0.325.0> Supervisor erly_room_sup_10 had child erly_room_worker_sup started with erly_room_worker_sup:start_link(10) at <0.327.0> exit with reason shutdown in context child_terminated
2018-03-26 11:20:29.005 [error] <0.347.0>@erly_room_worker:terminate:270 process terminate Reason {badarith,[{erly_room_worker,handle_call,3,[{file,"/home/henry/erly_room/_build/default/lib/erly_room/src/erly_room_worker.erl"},{line,123}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,615}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,647}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
2018-03-26 11:20:29.006 [error] <0.347.0> gen_server <0.347.0> terminated with reason: bad arithmetic expression in erly_room_worker:handle_call/3 line 123
2018-03-26 11:20:29.029 [error] <0.347.0> CRASH REPORT Process <0.347.0> with 0 neighbours exited with reason: bad arithmetic expression in erly_room_worker:handle_call/3 line 123 in gen_server:terminate/7 line 812
2018-03-26 11:20:29.029 [error] <0.345.0> Supervisor erly_room_worker_sup_10 had child erly_room_worker started with erly_room_worker:start_link({10,10000}) at <0.347.0> exit with reason bad arithmetic expression in erly_room_worker:handle_call/3 line 123 in context child_terminated
2018-03-26 11:20:29.030 [error] <0.351.0> CRASH REPORT Process <0.351.0> with 0 neighbours exited with reason: bad argument in call to ets:lookup(room_data, {10,10000}) in erly_room_worker:init/1 line 103
2018-03-26 11:20:29.031 [error] <0.345.0> Supervisor erly_room_worker_sup_10 had child erly_room_worker started with erly_room_worker:start_link({10,10000}) at <0.347.0> exit with reason bad argument in call to ets:lookup(room_data, {10,10000}) in erly_room_worker:init/1 line 103 in context start_error
2018-03-26 11:20:29.031 [error] <0.352.0> CRASH REPORT Process <0.352.0> with 0 neighbours exited with reason: bad argument in call to ets:lookup(room_data, {10,10000}) in erly_room_worker:init/1 line 103
2018-03-26 11:20:29.031 [error] <0.345.0> Supervisor erly_room_worker_sup_10 had child erly_room_worker started with erly_room_worker:start_link({10,10000}) at {restarting,<0.347.0>} exit with reason bad argument in call to ets:lookup(room_data, {10,10000}) in erly_room_worker:init/1 line 103 in context start_error
2018-03-26 11:20:29.032 [error] <0.353.0> CRASH REPORT Process <0.353.0> with 0 neighbours exited with reason: bad argument in call to ets:lookup(room_data, {10,10000}) in erly_room_worker:init/1 line 103
2018-03-26 11:20:29.032 [error] <0.345.0> Supervisor erly_room_worker_sup_10 had child erly_room_worker started with erly_room_worker:start_link({10,10000}) at {restarting,<0.347.0>} exit with reason bad argument in call to ets:lookup(room_data, {10,10000}) in erly_room_worker:init/1 line 103 in context start_error
2018-03-26 11:20:29.032 [error] <0.354.0> CRASH REPORT Process <0.354.0> with 0 neighbours exited with reason: bad argument in call to ets:lookup(room_data, {10,10000}) in erly_room_worker:init/1 line 103
2018-03-26 11:20:29.032 [error] <0.345.0> Supervisor erly_room_worker_sup_10 had child erly_room_worker started with erly_room_worker:start_link({10,10000}) at {restarting,<0.347.0>} exit with reason bad argument in call to ets:lookup(room_data, {10,10000}) in erly_room_worker:init/1 line 103 in context start_error
2018-03-26 11:20:29.032 [error] <0.355.0> CRASH REPORT Process <0.355.0> with 0 neighbours exited with reason: bad argument in call to ets:lookup(room_data, {10,10000}) in erly_room_worker:init/1 line 103
2018-03-26 11:20:29.032 [error] <0.345.0> Supervisor erly_room_worker_sup_10 had child erly_room_worker started with erly_room_worker:start_link({10,10000}) at {restarting,<0.347.0>} exit with reason bad argument in call to ets:lookup(room_data, {10,10000}) in erly_room_worker:init/1 line 103 in context start_error
2018-03-26 11:20:29.032 [error] <0.356.0> CRASH REPORT Process <0.356.0> with 0 neighbours exited with reason: bad argument in call to ets:lookup(room_data, {10,10000}) in erly_room_worker:init/1 line 103
2018-03-26 11:20:29.032 [error] <0.345.0> Supervisor erly_room_worker_sup_10 had child erly_room_worker started with erly_room_worker:start_link({10,10000}) at {restarting,<0.347.0>} exit with reason bad argument in call to ets:lookup(room_data, {10,10000}) in erly_room_worker:init/1 line 103 in context start_error
2018-03-26 11:20:29.032 [error] <0.345.0> Supervisor erly_room_worker_sup_10 had child erly_room_worker started with erly_room_worker:start_link({10,10000}) at {restarting,<0.347.0>} exit with reason bad argument in call to ets:lookup(room_data, {10,10000}) in erly_room_worker:init/1 line 103 in context start_error
2018-03-26 11:20:29.032 [error] <0.357.0> CRASH REPORT Process <0.357.0> with 0 neighbours exited with reason: bad argument in call to ets:lookup(room_data, {10,10000}) in erly_room_worker:init/1 line 103
2018-03-26 11:20:29.032 [error] <0.358.0> CRASH REPORT Process <0.358.0> with 0 neighbours exited with reason: bad argument in call to ets:lookup(room_data, {10,10000}) in erly_room_worker:init/1 line 103
2018-03-26 11:20:29.033 [error] <0.345.0> Supervisor erly_room_worker_sup_10 had child erly_room_worker started with erly_room_worker:start_link({10,10000}) at {restarting,<0.347.0>} exit with reason bad argument in call to ets:lookup(room_data, {10,10000}) in erly_room_worker:init/1 line 103 in context start_error
2018-03-26 11:20:29.033 [error] <0.359.0> CRASH REPORT Process <0.359.0> with 0 neighbours exited with reason: bad argument in call to ets:lookup(room_data, {10,10000}) in erly_room_worker:init/1 line 103
2018-03-26 11:20:29.033 [error] <0.345.0> Supervisor erly_room_worker_sup_10 had child erly_room_worker started with erly_room_worker:start_link({10,10000}) at {restarting,<0.347.0>} exit with reason bad argument in call to ets:lookup(room_data, {10,10000}) in erly_room_worker:init/1 line 103 in context start_error
2018-03-26 11:20:29.033 [error] <0.360.0> CRASH REPORT Process <0.360.0> with 0 neighbours exited with reason: bad argument in call to ets:lookup(room_data, {10,10000}) in erly_room_worker:init/1 line 103
2018-03-26 11:20:29.033 [error] <0.345.0> Supervisor erly_room_worker_sup_10 had child erly_room_worker started with erly_room_worker:start_link({10,10000}) at {restarting,<0.347.0>} exit with reason bad argument in call to ets:lookup(room_data, {10,10000}) in erly_room_worker:init/1 line 103 in context start_error
2018-03-26 11:20:29.033 [error] <0.345.0> Supervisor erly_room_worker_sup_10 had child erly_room_worker started with erly_room_worker:start_link({10,10000}) at {restarting,<0.347.0>} exit with reason reached_max_restart_intensity in context shutdown
2018-03-26 11:20:29.033 [error] <0.343.0> Supervisor erly_room_sup_10 had child erly_room_worker_sup started with erly_room_worker_sup:start_link(10) at <0.345.0> exit with reason shutdown in context child_terminated
2018-03-26 11:26:09.431 [error] <0.347.0>@erly_room_worker:terminate:270 process terminate Reason {badarith,[{erly_room_worker,handle_call,3,[{file,"/home/henry/erly_room/_build/default/lib/erly_room/src/erly_room_worker.erl"},{line,123}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,615}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,647}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
2018-03-26 11:26:09.436 [error] <0.347.0> gen_server <0.347.0> terminated with reason: bad arithmetic expression in erly_room_worker:handle_call/3 line 123
2018-03-26 11:26:09.448 [error] <0.347.0> CRASH REPORT Process <0.347.0> with 0 neighbours exited with reason: bad arithmetic expression in erly_room_worker:handle_call/3 line 123 in gen_server:terminate/7 line 812
2018-03-26 11:26:09.454 [error] <0.345.0> Supervisor erly_room_worker_sup_10 had child erly_room_worker started with erly_room_worker:start_link({10,10000}) at <0.347.0> exit with reason bad arithmetic expression in erly_room_worker:handle_call/3 line 123 in context child_terminated
2018-03-26 11:26:09.454 [error] <0.542.0> CRASH REPORT Process <0.542.0> with 0 neighbours exited with reason: bad argument in call to ets:lookup(room_data, {10,10000}) in erly_room_worker:init/1 line 103
2018-03-26 11:26:09.455 [error] <0.345.0> Supervisor erly_room_worker_sup_10 had child erly_room_worker started with erly_room_worker:start_link({10,10000}) at <0.347.0> exit with reason bad argument in call to ets:lookup(room_data, {10,10000}) in erly_room_worker:init/1 line 103 in context start_error
2018-03-26 11:26:09.455 [error] <0.543.0> CRASH REPORT Process <0.543.0> with 0 neighbours exited with reason: bad argument in call to ets:lookup(room_data, {10,10000}) in erly_room_worker:init/1 line 103
2018-03-26 11:26:09.455 [error] <0.345.0> Supervisor erly_room_worker_sup_10 had child erly_room_worker started with erly_room_worker:start_link({10,10000}) at {restarting,<0.347.0>} exit with reason bad argument in call to ets:lookup(room_data, {10,10000}) in erly_room_worker:init/1 line 103 in context start_error
2018-03-26 11:26:09.456 [error] <0.544.0> CRASH REPORT Process <0.544.0> with 0 neighbours exited with reason: bad argument in call to ets:lookup(room_data, {10,10000}) in erly_room_worker:init/1 line 103
2018-03-26 11:26:09.456 [error] <0.345.0> Supervisor erly_room_worker_sup_10 had child erly_room_worker started with erly_room_worker:start_link({10,10000}) at {restarting,<0.347.0>} exit with reason bad argument in call to ets:lookup(room_data, {10,10000}) in erly_room_worker:init/1 line 103 in context start_error
2018-03-26 11:26:09.456 [error] <0.545.0> CRASH REPORT Process <0.545.0> with 0 neighbours exited with reason: bad argument in call to ets:lookup(room_data, {10,10000}) in erly_room_worker:init/1 line 103
2018-03-26 11:26:09.456 [error] <0.345.0> Supervisor erly_room_worker_sup_10 had child erly_room_worker started with erly_room_worker:start_link({10,10000}) at {restarting,<0.347.0>} exit with reason bad argument in call to ets:lookup(room_data, {10,10000}) in erly_room_worker:init/1 line 103 in context start_error
2018-03-26 11:26:09.457 [error] <0.546.0> CRASH REPORT Process <0.546.0> with 0 neighbours exited with reason: bad argument in call to ets:lookup(room_data, {10,10000}) in erly_room_worker:init/1 line 103
2018-03-26 11:26:09.458 [error] <0.345.0> Supervisor erly_room_worker_sup_10 had child erly_room_worker started with erly_room_worker:start_link({10,10000}) at {restarting,<0.347.0>} exit with reason bad argument in call to ets:lookup(room_data, {10,10000}) in erly_room_worker:init/1 line 103 in context start_error
2018-03-26 11:26:09.458 [error] <0.547.0> CRASH REPORT Process <0.547.0> with 0 neighbours exited with reason: bad argument in call to ets:lookup(room_data, {10,10000}) in erly_room_worker:init/1 line 103
2018-03-26 11:26:09.458 [error] <0.345.0> Supervisor erly_room_worker_sup_10 had child erly_room_worker started with erly_room_worker:start_link({10,10000}) at {restarting,<0.347.0>} exit with reason bad argument in call to ets:lookup(room_data, {10,10000}) in erly_room_worker:init/1 line 103 in context start_error
2018-03-26 11:26:09.458 [error] <0.548.0> CRASH REPORT Process <0.548.0> with 0 neighbours exited with reason: bad argument in call to ets:lookup(room_data, {10,10000}) in erly_room_worker:init/1 line 103
2018-03-26 11:26:09.459 [error] <0.345.0> Supervisor erly_room_worker_sup_10 had child erly_room_worker started with erly_room_worker:start_link({10,10000}) at {restarting,<0.347.0>} exit with reason bad argument in call to ets:lookup(room_data, {10,10000}) in erly_room_worker:init/1 line 103 in context start_error
2018-03-26 11:26:09.459 [error] <0.549.0> CRASH REPORT Process <0.549.0> with 0 neighbours exited with reason: bad argument in call to ets:lookup(room_data, {10,10000}) in erly_room_worker:init/1 line 103
2018-03-26 11:26:09.459 [error] <0.345.0> Supervisor erly_room_worker_sup_10 had child erly_room_worker started with erly_room_worker:start_link({10,10000}) at {restarting,<0.347.0>} exit with reason bad argument in call to ets:lookup(room_data, {10,10000}) in erly_room_worker:init/1 line 103 in context start_error
2018-03-26 11:26:09.459 [error] <0.550.0> CRASH REPORT Process <0.550.0> with 0 neighbours exited with reason: bad argument in call to ets:lookup(room_data, {10,10000}) in erly_room_worker:init/1 line 103
2018-03-26 11:26:09.460 [error] <0.345.0> Supervisor erly_room_worker_sup_10 had child erly_room_worker started with erly_room_worker:start_link({10,10000}) at {restarting,<0.347.0>} exit with reason bad argument in call to ets:lookup(room_data, {10,10000}) in erly_room_worker:init/1 line 103 in context start_error
2018-03-26 11:26:09.460 [error] <0.551.0> CRASH REPORT Process <0.551.0> with 0 neighbours exited with reason: bad argument in call to ets:lookup(room_data, {10,10000}) in erly_room_worker:init/1 line 103
2018-03-26 11:26:09.460 [error] <0.345.0> Supervisor erly_room_worker_sup_10 had child erly_room_worker started with erly_room_worker:start_link({10,10000}) at {restarting,<0.347.0>} exit with reason bad argument in call to ets:lookup(room_data, {10,10000}) in erly_room_worker:init/1 line 103 in context start_error
2018-03-26 11:26:09.461 [error] <0.345.0> Supervisor erly_room_worker_sup_10 had child erly_room_worker started with erly_room_worker:start_link({10,10000}) at {restarting,<0.347.0>} exit with reason reached_max_restart_intensity in context shutdown
2018-03-26 11:26:09.461 [error] <0.343.0> Supervisor erly_room_sup_10 had child erly_room_worker_sup started with erly_room_worker_sup:start_link(10) at <0.345.0> exit with reason shutdown in context child_terminated
2018-03-26 11:28:09.822 [error] <0.347.0>@erly_room_worker:terminate:270 process terminate Reason {badarith,[{erly_room_worker,handle_call,3,[{file,"/home/henry/erly_room/_build/default/lib/erly_room/src/erly_room_worker.erl"},{line,123}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,615}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,647}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
2018-03-26 11:28:09.822 [error] <0.347.0> gen_server <0.347.0> terminated with reason: bad arithmetic expression in erly_room_worker:handle_call/3 line 123
2018-03-26 11:28:09.843 [error] <0.347.0> CRASH REPORT Process <0.347.0> with 0 neighbours exited with reason: bad arithmetic expression in erly_room_worker:handle_call/3 line 123 in gen_server:terminate/7 line 812
2018-03-26 11:28:09.844 [error] <0.345.0> Supervisor erly_room_worker_sup_10 had child erly_room_worker started with erly_room_worker:start_link({10,10000}) at <0.347.0> exit with reason bad arithmetic expression in erly_room_worker:handle_call/3 line 123 in context child_terminated
2018-03-26 11:28:09.845 [error] <0.363.0> CRASH REPORT Process <0.363.0> with 0 neighbours exited with reason: bad argument in call to ets:lookup(room_data, {10,10000}) in erly_room_worker:init/1 line 103
2018-03-26 11:28:09.847 [error] <0.345.0> Supervisor erly_room_worker_sup_10 had child erly_room_worker started with erly_room_worker:start_link({10,10000}) at <0.347.0> exit with reason bad argument in call to ets:lookup(room_data, {10,10000}) in erly_room_worker:init/1 line 103 in context start_error
2018-03-26 11:28:09.847 [error] <0.364.0> CRASH REPORT Process <0.364.0> with 0 neighbours exited with reason: bad argument in call to ets:lookup(room_data, {10,10000}) in erly_room_worker:init/1 line 103
2018-03-26 11:28:09.848 [error] <0.345.0> Supervisor erly_room_worker_sup_10 had child erly_room_worker started with erly_room_worker:start_link({10,10000}) at {restarting,<0.347.0>} exit with reason bad argument in call to ets:lookup(room_data, {10,10000}) in erly_room_worker:init/1 line 103 in context start_error
2018-03-26 11:28:09.849 [error] <0.365.0> CRASH REPORT Process <0.365.0> with 0 neighbours exited with reason: bad argument in call to ets:lookup(room_data, {10,10000}) in erly_room_worker:init/1 line 103
2018-03-26 11:28:09.849 [error] <0.345.0> Supervisor erly_room_worker_sup_10 had child erly_room_worker started with erly_room_worker:start_link({10,10000}) at {restarting,<0.347.0>} exit with reason bad argument in call to ets:lookup(room_data, {10,10000}) in erly_room_worker:init/1 line 103 in context start_error
2018-03-26 11:28:09.849 [error] <0.366.0> CRASH REPORT Process <0.366.0> with 0 neighbours exited with reason: bad argument in call to ets:lookup(room_data, {10,10000}) in erly_room_worker:init/1 line 103
2018-03-26 11:28:09.849 [error] <0.345.0> Supervisor erly_room_worker_sup_10 had child erly_room_worker started with erly_room_worker:start_link({10,10000}) at {restarting,<0.347.0>} exit with reason bad argument in call to ets:lookup(room_data, {10,10000}) in erly_room_worker:init/1 line 103 in context start_error
2018-03-26 11:28:09.849 [error] <0.367.0> CRASH REPORT Process <0.367.0> with 0 neighbours exited with reason: bad argument in call to ets:lookup(room_data, {10,10000}) in erly_room_worker:init/1 line 103
2018-03-26 11:28:09.850 [error] <0.345.0> Supervisor erly_room_worker_sup_10 had child erly_room_worker started with erly_room_worker:start_link({10,10000}) at {restarting,<0.347.0>} exit with reason bad argument in call to ets:lookup(room_data, {10,10000}) in erly_room_worker:init/1 line 103 in context start_error
2018-03-26 11:28:09.850 [error] <0.368.0> CRASH REPORT Process <0.368.0> with 0 neighbours exited with reason: bad argument in call to ets:lookup(room_data, {10,10000}) in erly_room_worker:init/1 line 103
2018-03-26 11:28:09.852 [error] <0.345.0> Supervisor erly_room_worker_sup_10 had child erly_room_worker started with erly_room_worker:start_link({10,10000}) at {restarting,<0.347.0>} exit with reason bad argument in call to ets:lookup(room_data, {10,10000}) in erly_room_worker:init/1 line 103 in context start_error
2018-03-26 11:28:09.852 [error] <0.369.0> CRASH REPORT Process <0.369.0> with 0 neighbours exited with reason: bad argument in call to ets:lookup(room_data, {10,10000}) in erly_room_worker:init/1 line 103
2018-03-26 11:28:09.852 [error] <0.345.0> Supervisor erly_room_worker_sup_10 had child erly_room_worker started with erly_room_worker:start_link({10,10000}) at {restarting,<0.347.0>} exit with reason bad argument in call to ets:lookup(room_data, {10,10000}) in erly_room_worker:init/1 line 103 in context start_error
2018-03-26 11:28:09.853 [error] <0.370.0> CRASH REPORT Process <0.370.0> with 0 neighbours exited with reason: bad argument in call to ets:lookup(room_data, {10,10000}) in erly_room_worker:init/1 line 103
2018-03-26 11:28:09.853 [error] <0.345.0> Supervisor erly_room_worker_sup_10 had child erly_room_worker started with erly_room_worker:start_link({10,10000}) at {restarting,<0.347.0>} exit with reason bad argument in call to ets:lookup(room_data, {10,10000}) in erly_room_worker:init/1 line 103 in context start_error
2018-03-26 11:28:09.853 [error] <0.371.0> CRASH REPORT Process <0.371.0> with 0 neighbours exited with reason: bad argument in call to ets:lookup(room_data, {10,10000}) in erly_room_worker:init/1 line 103
2018-03-26 11:28:09.854 [error] <0.345.0> Supervisor erly_room_worker_sup_10 had child erly_room_worker started with erly_room_worker:start_link({10,10000}) at {restarting,<0.347.0>} exit with reason bad argument in call to ets:lookup(room_data, {10,10000}) in erly_room_worker:init/1 line 103 in context start_error
2018-03-26 11:28:09.854 [error] <0.345.0> Supervisor erly_room_worker_sup_10 had child erly_room_worker started with erly_room_worker:start_link({10,10000}) at {restarting,<0.347.0>} exit with reason bad argument in call to ets:lookup(room_data, {10,10000}) in erly_room_worker:init/1 line 103 in context start_error
2018-03-26 11:28:09.854 [error] <0.372.0> CRASH REPORT Process <0.372.0> with 0 neighbours exited with reason: bad argument in call to ets:lookup(room_data, {10,10000}) in erly_room_worker:init/1 line 103
2018-03-26 11:28:09.854 [error] <0.345.0> Supervisor erly_room_worker_sup_10 had child erly_room_worker started with erly_room_worker:start_link({10,10000}) at {restarting,<0.347.0>} exit with reason reached_max_restart_intensity in context shutdown
2018-03-26 11:28:09.855 [error] <0.343.0> Supervisor erly_room_sup_10 had child erly_room_worker_sup started with erly_room_worker_sup:start_link(10) at <0.345.0> exit with reason shutdown in context child_terminated
2018-03-26 14:03:56.616 [error] <0.329.0>@erly_room_worker:terminate:270 process terminate Reason {function_clause,[{string,substr2,[undefined,5],[{file,"string.erl"},{line,213}]},{erly_room_worker,mask_name,1,[{file,"/home/henry/erly_room/_build/default/lib/erly_room/src/erly_room_worker.erl"},{line,419}]},{erly_room_worker,'-broadcast/5-lc$^0/1-0-',1,[{file,"/home/henry/erly_room/_build/default/lib/erly_room/src/erly_room_worker.erl"},{line,305}]},{erly_room_worker,'-broadcast/5-lc$^0/1-0-',1,[{file,"/home/henry/erly_room/_build/default/lib/erly_room/src/erly_room_worker.erl"},{line,305}]},{erly_room_worker,broadcast,5,[{file,"/home/henry/erly_room/_build/default/lib/erly_room/src/erly_room_worker.erl"},{line,305}]},{erly_room_worker,is_room_full,3,[{file,"/home/henry/erly_room/_build/default/lib/erly_room/src/erly_room_worker.erl"},{line,376}]},{erly_room_worker,handle_cast,2,[{file,"/home/henry/erly_room/_build/default/lib/erly_room/src/erly_room_worker.erl"},{line,136}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,601}]}]}
2018-03-26 14:03:56.621 [error] <0.329.0> gen_server <0.329.0> terminated with reason: no function clause matching string:substr2(undefined, 5) line 213
2018-03-26 14:03:56.634 [error] <0.329.0> CRASH REPORT Process <0.329.0> with 0 neighbours exited with reason: no function clause matching string:substr2(undefined, 5) line 213 in gen_server:terminate/7 line 812
2018-03-26 14:03:56.635 [error] <0.327.0> Supervisor erly_room_worker_sup_10 had child erly_room_worker started with erly_room_worker:start_link({10,10000}) at <0.329.0> exit with reason no function clause matching string:substr2(undefined, 5) line 213 in context child_terminated
2018-03-26 14:04:25.763 [error] <0.344.0>@erly_room_worker:terminate:270 process terminate Reason {function_clause,[{string,substr2,[undefined,5],[{file,"string.erl"},{line,213}]},{erly_room_worker,mask_name,1,[{file,"/home/henry/erly_room/_build/default/lib/erly_room/src/erly_room_worker.erl"},{line,419}]},{erly_room_worker,'-broadcast/5-lc$^0/1-0-',1,[{file,"/home/henry/erly_room/_build/default/lib/erly_room/src/erly_room_worker.erl"},{line,305}]},{erly_room_worker,'-broadcast/5-lc$^0/1-0-',1,[{file,"/home/henry/erly_room/_build/default/lib/erly_room/src/erly_room_worker.erl"},{line,305}]},{erly_room_worker,broadcast,5,[{file,"/home/henry/erly_room/_build/default/lib/erly_room/src/erly_room_worker.erl"},{line,305}]},{erly_room_worker,is_room_full,3,[{file,"/home/henry/erly_room/_build/default/lib/erly_room/src/erly_room_worker.erl"},{line,376}]},{erly_room_worker,handle_cast,2,[{file,"/home/henry/erly_room/_build/default/lib/erly_room/src/erly_room_worker.erl"},{line,136}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,601}]}]}
2018-03-26 14:04:25.765 [error] <0.344.0> gen_server <0.344.0> terminated with reason: no function clause matching string:substr2(undefined, 5) line 213
2018-03-26 14:04:25.766 [error] <0.344.0> CRASH REPORT Process <0.344.0> with 0 neighbours exited with reason: no function clause matching string:substr2(undefined, 5) line 213 in gen_server:terminate/7 line 812
2018-03-26 14:04:25.767 [error] <0.327.0> Supervisor erly_room_worker_sup_10 had child erly_room_worker started with erly_room_worker:start_link({10,10000}) at <0.344.0> exit with reason no function clause matching string:substr2(undefined, 5) line 213 in context child_terminated
2018-03-26 18:02:24.318 [error] <0.385.0> gen_server erly_room_manage_10 terminated with reason: {unknown_cast,{refresh_room_num,user_join,1,#{user_id => 444,user_name => "ddddd"},444,4}}
2018-03-26 18:02:24.357 [error] <0.385.0> CRASH REPORT Process erly_room_manage_10 with 0 neighbours exited with reason: {unknown_cast,{refresh_room_num,user_join,1,#{user_id => 444,user_name => "ddddd"},444,4}} in gen_server:terminate/7 line 812
2018-03-26 18:02:24.357 [error] <0.384.0> Supervisor erly_room_sup_10 had child erly_room_manage started with erly_room_manage:start_link(10) at <0.385.0> exit with reason {unknown_cast,{refresh_room_num,user_join,1,#{user_id => 444,user_name => "ddddd"},444,4}} in context child_terminated
2018-03-26 18:08:27.751 [error] <0.329.0> gen_server <0.329.0> terminated with reason: no function clause matching string:substr2(undefined, 5) line 213
2018-03-26 18:08:27.766 [error] <0.329.0> CRASH REPORT Process <0.329.0> with 0 neighbours exited with reason: no function clause matching string:substr2(undefined, 5) line 213 in gen_server:terminate/7 line 812
2018-03-26 18:08:27.766 [error] <0.327.0> Supervisor erly_room_worker_sup_10 had child erly_room_worker started with erly_room_worker:start_link({10,10000}) at <0.329.0> exit with reason no function clause matching string:substr2(undefined, 5) line 213 in context child_terminated
